In [37]:
# Required
from math import sin, cos, tan, pi, atan, degrees, radians, pi, e, pow, log

In [38]:
d_mean = 30/1000
P_load=6000
efficiency=0.4
screw_type = 1 # single-start
alpha_n = 14.28
lambda_helix = 10.31
f_screw = 0.15
f_collar = 0
d_collar = 0

i)

In [39]:
print(f'3 factors that effects efficiency:\n1. Frictional coefficient of screw and collar\n2. Lead angle (helix angle)\n3. Mean diameter of the screw')

3 factors that effects efficiency:
1. Frictional coefficient of screw and collar
2. Lead angle (helix angle)
3. Mean diameter of the screw


ii)

In [40]:
tan_lambda = tan(radians(lambda_helix))
print(f'tan_lambda: {tan_lambda}')

tan_lambda: 0.18191110285058593


In [41]:
f_screw = 0.2
print(f'f_screw: {f_screw}')

f_screw: 0.2


In [42]:
check_self_locking = cos(radians(alpha_n))*tan_lambda
print(f'check_self_locking: {check_self_locking}')

check_self_locking: 0.17629039381910316


In [43]:
print(f'Self-locking because {f_screw} > {check_self_locking}')

Self-locking because 0.2 > 0.17629039381910316


iii) If screw is changed to square thread

In [44]:
alpha_n=0
f_screw=0.15
efficiency=(d_mean*tan_lambda)/(d_mean*((f_screw+(cos(radians(alpha_n))*tan_lambda))/(cos(radians(alpha_n))-(f_screw*tan_lambda)))+(d_collar*f_collar))
print(f'efficiency: {efficiency:.4f}')

efficiency: 0.5331


b)

In [45]:
Pload=46000
Nbolt=6
FOS=2.6
Sp=650e6
print(f'Class 8.8 bolt proof strength: {Sp/1e6} MPa')
# Eb=2*Ep
# Ap =3*Ab

Class 8.8 bolt proof strength: 650.0 MPa


$$C = \frac{k_b}{k_b + K_p}$$
$$ = \frac{\frac{A_b E_b}{L}}{\frac{A_b E_b}{L} + \frac{A_p E_p}{L}} $$
$$= \frac{\frac{A_b 2 E_p}{L}}{\frac{A_b 2 E_p}{L} + \frac{3 A_b E_p}{L}} $$
$$= \frac{2}{5} = 0.4$$

In [46]:
C=0.4

$$S_p A_t= C\left(\frac{P}{N}\right)n + F_i$$
$$650\times 10^6 A_t= 0.4\left(\frac{46\times 10^3}{6}\right)2.6 + 0.75 (650\times 10^6 A_t)$$

In [47]:
A_t=C*(Pload/Nbolt)*FOS/(Sp*(1-0.75))
print(f'A_t: {A_t:.3e} m^2')
print(f'A_t: {A_t*1e6:.2f} mm^2')
print(f'From Table At= 58 mm^2 with d=10mm')

A_t: 4.907e-05 m^2
A_t: 49.07 mm^2
From Table At= 58 mm^2 with d=10mm


ii)

In [48]:
Nbolt=4
Fbolt=C*(Pload/Nbolt)*FOS+(0.75*Sp*A_t)
print(f'Fbolt: {Fbolt:.2f} N')

Fbolt: 35880.00 N


In [49]:
print(f'External load per bolt: {Pload/Nbolt:.2f} N')

External load per bolt: 11500.00 N


In [50]:
print(f'{Fbolt:.2f}N > {Pload/Nbolt:.2f}N, thus the design is not separated.')

35880.00N > 11500.00N, thus the design is not separated.


iii)

In [51]:
Sp=450e6
print(f'Class 4.6 bolt proof strength: {Sp/1e6} MPa')
d=10/1000
A_t=58e-6
print(f'From Table, d= {d*1000} mm, A_t: {A_t*1e6:.2f} mm^2')
Nbolt=6
C=0.4

Class 4.6 bolt proof strength: 450.0 MPa
From Table, d= 10.0 mm, A_t: 58.00 mm^2


$$S_p A_t= C\left(\frac{P}{N}\right)n + F_i$$
$$450\times 10^6 (58\times 10^{-6})= 0.4\left(\frac{46\times 10^3}{6}\right)n + 0.75 (450\times 10^6 (58\times 10^{-6}))$$

In [52]:
FOS=(Sp*A_t*(1-0.75))*Nbolt/(Pload*C)
print(f'FOS: {FOS:.2f}')

FOS: 2.13
